### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by WUyinwei-hah** [JeongminB/E-D3DGS#1]
Hi, great work! May I ask when would you release the code?

**Comment by JeongminB** [comment]
Hello, we expect to release the code around June 2024.
However, the above date can change based on the situation.

Thanks for your interest!

**Comment by seoha-kim** [comment]
The code is released.
We have been working on several research projects simultaneously, 
so it's taken us a bit longer to release the code. 
Thanks so much for your interest. 🙏🏻
