### ISSUE TITLE
Regarding the discrepancy in experimental results of cut_roasted_beef in N3DV dataset.

### ISSUE THREAD

**Issue by LabubuJ** [JeongminB/E-D3DGS#10]
Thank you for your excellent work. When I tested your model, the results deviated significantly from those reported in the paper. I would like to understand the reason for this discrepancy and learn how I can achieve better results.
My results are as follows.
❯  cd /home/disk1/jh/E-D3DGS ; /usr/bin/env /bin/python3 /home/zzj/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 55679 -- ./metrics.py --model_path /home/disk1/jh/E-D3DGS/output/cut_roasted_beef

Scene: /home/disk1/jh/E-D3DGS/output/cut_roasted_beef
Method: ours_80000
Metric evaluation progress:   0%|                                                                         | 0/300 [00:00<?, ?it/s]Downloading: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/vgg.pth" to /home/zzj/.cache/torch/hub/checkpoints/vgg.pth
100%|████████████████████████████████████████████████████████████████████████████████████████| 7.12k/7.12k [00:02<00:00, 3.10kB/s]
/home/disk1/jh/conda_envs/ed3dgs/lib/python3.7/site-packages/torchvision/models/_utils.py:136: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  f"Using {sequence_to_str(tuple(keyword_only_kwargs.keys()), separate_last='and ')} as positional "
/home/disk1/jh/conda_envs/ed3dgs/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /home/zzj/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████| 233M/233M [02:11<00:00, 1.86MB/s]
Downloading: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/alex.pth" to /home/zzj/.cache/torch/hub/checkpoints/alex.pth
100%|████████████████████████████████████████████████████████████████████████████████████████| 5.87k/5.87k [00:00<00:00, 3.06MB/s]
Metric evaluation progress: 100%|███████████████████████████████████████████████████████████████| 300/300 [10:52<00:00,  2.18s/it]
Scene:  /home/disk1/jh/E-D3DGS/output/cut_roasted_beef SSIM :    0.9286678
Scene:  /home/disk1/jh/E-D3DGS/output/cut_roasted_beef PSNR :   29.9824677
Scene:  /home/disk1/jh/E-D3DGS/output/cut_roasted_beef LPIPS_VGG:    0.1424698
Scene:  /home/disk1/jh/E-D3DGS/output/cut_roasted_beef LPIPS_ALEX:    0.0451441
The PSNR and SSIM values are significantly different from the 33.57 and 0.958 provided in the paper.
Thanks for your response！

**Comment by JiaoChenGuang-JiaoHan** [comment]
Hello, after my observation, your method performs excellently in reconstructing dynamic parts, but the color tone differs significantly from the ground truth. Perhaps this is the reason for the large discrepancy in PSNR? I would like to know your thoughts on this matter. The highest PSNR I tested is 32.98.

**Comment by seoha-kim** [comment]
Hello.
I am sorry for the late reply.
I uploaded the checkpoints, configs, and rendered video for the paper results [here](https://drive.google.com/drive/folders/1PAaIp5cNYNpLjQ5JX0SVLh5Yn_K9UmJd?usp=sharing)
Please take a look at the above link. 

I appreciate your interest in our work.
