### ISSUE TITLE
How to achieve the best performance of 4DGaussians on Technicolor Dataset

### ISSUE THREAD

**Issue by liyw420** [JeongminB/E-D3DGS#11]
Hello! Thank you for your great work!

Recently I've been reproducing the results of Dynamic GS models on dynamic scene datasets. Your work is really brilliant! 

When I test the model of 4DGaussians [1] on the technicolor dataset, I found that the final results are really poor.  Although I cannot guarantee I handle all the inputs well (camera parameters, point clouds, and images), I guess the poor results are caused by the settings of hyperparameters. Given that you've reproduced this model on this dataset, I was wondering if you could give me some suggestions on this issue? 

Thank you!!! 

Poor rendered image:
Train view:
![00149](https://github.com/user-attachments/assets/b98b8627-957d-4fa9-8cc4-10b8879d8642)
Test view:
![00049](https://github.com/user-attachments/assets/db8198c9-249f-4532-ad0f-207df23d0f51)

Reference: 4D Gaussian Splatting for Real-Time Dynamic Scene Rendering, CVPR 2024.

**Comment by seoha-kim** [comment]
Hello.
I am sorry for the late reply.
I uploaded the checkpoints, configs, and rendered videos for the paper results [here](https://drive.google.com/drive/folders/1PAaIp5cNYNpLjQ5JX0SVLh5Yn_K9UmJd?usp=sharing)
Please take a look at the above link. 

I appreciate your interest in our work.

**Comment by chenj02** [comment]
> Hello. I am sorry for the late reply. I uploaded the checkpoints, configs, and rendered videos for the paper results [here](https://drive.google.com/drive/folders/1PAaIp5cNYNpLjQ5JX0SVLh5Yn_K9UmJd?usp=sharing) Please take a look at the above link.
> 
> I appreciate your interest in our work.

Hi, I met the same problem. How do you train 4D Gaussian? I can't get good results.

**Comment by seoha-kim** [comment]
I have never encountered poor results before, so I don't know the exact reason for the difference. But, I believe the poor results stem from a mismatch in frame numbers. As you're aware, there are broken images in the Technicolor dataset. To address the missing frames, I converted 300-frame images to .mp4 format and then converted them back to images. This interpolation allowed me to handle the broken frames and evaluate all baselines using the same images. (But I think it is not common preprocessing, as other papers simply drop the missing frame as hyperreel.) I suspect you have the original Technicolor images, which could be causing a frame mismatch. Please let me know if the same issue persists after the preprocessing steps. Then, I'll check if there are any differences in COLMAP preprocessing after refactoring the code. And I recommend you to using the uploaded folder. It contains the original cameras.json, input.ply, and configs which are used for the final results.

**Comment by chenj02** [comment]
> I have never encountered poor results before, so I don't know the exact reason for the difference. But, I believe the poor results stem from a mismatch in frame numbers. As you're aware, there are broken images in the Technicolor dataset. To address the missing frames, I converted 300-frame images to .mp4 format and then converted them back to images. This interpolation allowed me to handle the broken frames and evaluate all baselines using the same images. (But I think it is not common preprocessing, as other papers simply drop the missing frame as hyperreel.) I suspect you have the original Technicolor images, which could be causing a frame mismatch. Please let me know if the same issue persists after the preprocessing steps. Then, I'll check if there are any differences in COLMAP preprocessing after refactoring the code. And I recommend you to using the uploaded folder. It contains the original cameras.json, input.ply, and configs which are used for the final results.

In dataset Technicolor Train, I follow the instruction to get point cloud, and only use the first frame of the images to optimize the 3DGS of the static scene, but it's still fail to get good results. I don't know why. Can you give me some help? Very thanks!
point cloud：
![image](https://github.com/user-attachments/assets/33733f77-48db-4dbd-9b56-bafe7e60e6c0)
GT:
![image](https://github.com/user-attachments/assets/e21cf595-42e6-4797-b243-e769a291e0b5)
3DGS:
![image](https://github.com/user-attachments/assets/76a42ef9-df8d-40dc-a125-abbd7d6687a0)

**Comment by seoha-kim** [comment]
Could you use the configs in the above link and see the results?
It might also be helpful for me to show the rendered video using Google drive link.

**Comment by liyw420** [comment]
> Could you use the configs in the above link and see the results? It might also be helpful for me to show the rendered video using Google drive link.

Hello, sorry to bother you again. 

I have successfully run your code on the Technicolor Dataset with good results. However, I cannot achieve good results of 4DGaussians on Technicolor Dataset, as shown in the Figure I've uploaded. I use the point clouds and camera poses estimated by the pipline from your code. 

While E-D3DGS runs successfully, 4D Gaussians always fail in both training views and the test view. This indicate that the poor results may don't come from the preprocessing of the Technicolor Dataset, as E-D3DGS works.

I was wondering if you could provide the preprocessing-training-rendering details of 4DGaussians on the Technicolor Dataset? Does 4DGaussians undergoes the same preprocessing process as in E-D3DGS? Thank you!

**Comment by seoha-kim** [comment]
Ah, you mean 4DGaussians instead of our E-D3DGS. Sorry for being misunderstood.
If you give me your email address, I'll give you the configs of 4DGaussians. 
As written in the paper
(We followed the official code and configuration, except for increasing the training iterations for the Technicolor dataset to 1.5 times),
We increased the training iteration due to the low quality of 4DGaussians.

**Comment by chenj02** [comment]
> Could you use the configs in the above link and see the results? It might also be helpful for me to show the rendered video using Google drive link.

I don't train all images (dynamic) with E-D3DGS, instead, I train with original 3DGS -- I just use all cameras' first frame (it is a static scene) to get ponit cloud (which looks very good), and then use it to train 3DGS, but the results are very poor as I mentioned before.(I follow the instruction 'python script/pre_technicolor.py --videopath <dataset>/<scene>')

**Comment by chenj02** [comment]
> > Could you use the configs in the above link and see the results? It might also be helpful for me to show the rendered video using Google drive link.
> 
> Hello, sorry to bother you again.
> 
> I have successfully run your code on the Technicolor Dataset with good results. However, I cannot achieve good results of 4DGaussians on Technicolor Dataset, as shown in the Figure I've uploaded. I use the point clouds and camera poses estimated by the pipline from your code.
> 
> While E-D3DGS runs successfully, 4D Gaussians always fail in both training views and the test view. This indicate that the poor results may don't come from the preprocessing of the Technicolor Dataset, as E-D3DGS works.
> 
> I was wondering if you could provide the preprocessing-training-rendering details of 4DGaussians on the Technicolor Dataset? Does 4DGaussians undergoes the same preprocessing process as in E-D3DGS? Thank you!

I can't train with 4DGaussian either. I also try to use 3DGS train first frame to look whether it’s due to the data processing. But 3DGS‘s results are poor like 4DGaussian, so I suspect there are some error when using the point clouds and camera poses, but I haven't found it yet.

**Comment by seoha-kim** [comment]
I've remembered that Technicolor dataset has multiple camera intrinsic. 
So if you simply used N3V loader from 4DGaussians, it would produce bad results, since N3V dataset has only one shared intrinsic.
I combined the Technicolor loader and corresponding camera utils from STG to train 4DGaussians.
If you want, I can share 4DGaussians+Technicolor codes. (But it is messy ,, ㅠ.ㅠ)

**Comment by liyw420** [comment]
> I've remembered that Technicolor dataset has multiple camera intrinsic. So if you simply used N3V loader from 4DGaussians, it would produce bad results, since N3V dataset has only one shared intrinsic. I combined the Technicolor loader and corresponding camera utils from STG to train 4DGaussians. If you want, I can share 4DGaussians+Technicolor codes. (But it is messy ,, ㅠ.ㅠ)

Here is my e-mail: yiwei.vincent@gmail.com
Many, many thanks to you!

**Comment by seoha-kim** [comment]
I'll give you the code after finishing my work.
Do you want the results of 4DGaussians itself or code?

**Comment by liyw420** [comment]
> I'll give you the code after finishing my work.
> Do you want the results of 4DGaussians itself or code?
I want the code, thank you!

**Comment by chenj02** [comment]
> I've remembered that Technicolor dataset has multiple camera intrinsic. So if you simply used N3V loader from 4DGaussians, it would produce bad results, since N3V dataset has only one shared intrinsic. I combined the Technicolor loader and corresponding camera utils from STG to train 4DGaussians. If you want, I can share 4DGaussians+Technicolor codes. (But it is messy ,, ㅠ.ㅠ)

This is my email: chenjie02@mail.ustc.edu.cn, thanks very much if you share me with your 4DGaussians+Technicolor codes, very very thanks !!!

**Comment by liyw420** [comment]
I think I have solved my problem. Please refer to this repo: https://github.com/juno181/Ex4DGS/issues/17. 

Thank you all for your help!

**Comment by chenj02** [comment]
Thank you very much, I have solved my problem!

**Comment by LabubuJ** [comment]
> I'll give you the code after finishing my work. Do you want the results of 4DGaussians itself or code?

Could you please share your 4D Gaussians + Technicolor codes and results with me? Thank you! My email is csjh@zju.edu.cn

**Comment by chenj02** [comment]
> I'll give you the code after finishing my work. Do you want the results of 4DGaussians itself or code?

Sorry to bother you again. Although I have corrected the data processing on Technicolor, I still can't get good results which may be the problem of hyperparamters. Could you please share your 4D Gaussians + Technicolor codes and results with me? Thank you! My email is chenjie02@mail.ustc.edu.cn

**Comment by seoha-kim** [comment]
https://drive.google.com/file/d/14NmLy4N8VTFK8A7PBvbbwQYCAKtfJ4VZ/view?usp=sharing
I uploaded rendered videos and code. 

But its dataloader is from STG,
so you have to change the dataloader as 4DGaussians or dataset format as STG. 
(But I think the easiest way is merging ed3dgs technicolor loader into 4DGaussians)

Here is my folder tree

<img width="184" alt="Image" src="https://github.com/user-attachments/assets/51783106-9b0e-44c0-bfaa-ef86d018f6c9" />

**Comment by QAQ0302** [comment]
> https://drive.google.com/file/d/14NmLy4N8VTFK8A7PBvbbwQYCAKtfJ4VZ/view?usp=sharing I uploaded rendered videos and code.
> 
> But its dataloader is from STG, so you have to change the dataloader as 4DGaussians or dataset format as STG. (But I think the easiest way is merging ed3dgs technicolor loader into 4DGaussians)
> 
> Here is my folder tree
> 
> <img alt="Image" width="184" src="https://private-user-images.githubusercontent.com/46925617/420168551-51783106-9b0e-44c0-bfaa-ef86d018f6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk0NTM0MDUsIm5iZiI6MTc0OTQ1MzEwNSwicGF0aCI6Ii80NjkyNTYxNy80MjAxNjg1NTEtNTE3ODMxMDYtOWIwZS00NGMwLWJmYWEtZWY4NmQwMThmNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjA5VDA3MTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyN2NkZGZkZjgyMzJmYTgzZTRmM2Q1Y2U5YTFiZTliZDhkZGMzNzg0YmMzNTkzYTU0Nzk2YmMxZDZiMzkzODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3vOo9x5vwONtjVAHjxTl-dVTbUnExzgHgWY-Ufz0nYo">

Hi, I'm currently trying to make the Technicolor dataset work with 4DGaussians, and I ran into the same issue you mentioned.

It seems that the link you shared back in March is no longer working.
Could you please re-share your 4DGaussians + Technicolor code and results with me?

That would be really helpful. Thank you so much in advance!
Here’s my email: 3319858824@qq.com
