### ISSUE TITLE
About the Selection of the Technicolor Dataset

### ISSUE THREAD

**Issue by LabubuJ** [JeongminB/E-D3DGS#12]
Hello, thanks for your great work. I noticed that in the Technicolor dataset, there are two folders named png and ppm. Each of these folders contains three subdirectories: Original, Pseudo-rectified, and Undistorted. Could you clarify which type of data you used from these folders?

**Comment by JeongminB** [comment]
Hello, thank you for your interest in our work! We used undistorted PNGs following STG [(link)](https://github.com/oppo-us-research/SpacetimeGaussians?tab=readme-ov-file#technicolor-dataset)
