### ISSUE TITLE
densify strategy

### ISSUE THREAD

**Issue by tb2-sy** [JeongminB/E-D3DGS#2]
Thanks for your nice work!
After reading your paper, I did not find out how your method densify and prune during the training process. In [4DGS](https://github.com/hustvl/4DGaussians), position gradient in canonical space is used for densification. Do you also use this method?

**Comment by JeongminB** [comment]
I'm sorry for the delay in my response.

As you mentioned, we are using the same densification method as 4DGS. In certain scenes, our method can still produce blurry results in dynamic regions, and it would be interesting to consider a better densification method to address it. 
Thank you for your interest!
