### ISSUE TITLE
How to downsample in training?

### ISSUE THREAD

**Issue by zeshunzong** [JeongminB/E-D3DGS#4]
Thanks for the nice work!

A quick question on downsampling. If I want to make the training faster by downsampling the training data, what is the most convenient way to achieve that?

**Comment by seoha-kim** [comment]
Thank you for your interest.
We need this operation as well, so we'll check it and get back to you within a day. 😀

**Comment by JeongminB** [comment]
Hello!

You can downsample training images with `-r` or `--resolution` option (same as [3DGS](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#--resolution---r-1)). 
For example, if you add `-r 2` argument to the command line, the training resolution will be 507 x 676 for the n3v dataset. (default is `-r 1`)

**Comment by zeshunzong** [comment]
by the way thanks for also fixing the loss_list index out of bound issue!

there is an annoying print in train.py line 151, it would be perfect if that is removed!
