### ISSUE TITLE
A magic number seems to limit the number of cameras allowed?

### ISSUE THREAD

**Issue by zeshunzong** [JeongminB/E-D3DGS#5]
In deformation.py `self.offsets = torch.nn.Parameter(torch.zeros((30, 1)))
`
What does this magic number 30 mean? It seems that I get an error when data has more than 30 cameras.

**Comment by JeongminB** [comment]
You can simply increase that number (We added a comment to prevent confusion). 
We only verified the datasets we tested, and we leave the others to future researchers for now.
