### ISSUE TITLE
Question on Memory

### ISSUE THREAD

**Issue by 1305long** [JeongminB/E-D3DGS#7]
Hello, I ran out of 32G memory during the training. I want to know how much memory is needed for the complete training.

**Comment by JeongminB** [comment]
In my experience, training with a single 24G GPU has not been a problem. 
However, depending on the scene, an excessive number of Gaussians can lead to OOM issues. 

The simple solution is to increase the values of `densify_grad_threshold_fine_init` and `densify_grad_threshold_fine_after` to reduce the total number of Gaussians. 
Alternatively, you might consider using a smaller value for `lambda_dssim` or disable it (set to 0).

**Comment by Peamon** [comment]
Hi, the processus takes a lot of RAM and i finally get a OOM (on pagefile.sys) cause no space left on my disk.
Does the code have a memory leak or what parameter should i change to avoid this error ?

In your experience how much RAM memory use your process when training on cook_spinach ?

![image](https://github.com/user-attachments/assets/e0a1d668-1570-4930-8d04-037dad0b4f0a)
